export const ABILITY_ID = {
	//Unit Abilities
	HEAL: FourCC('a000'),
	ROAR: FourCC('a001'),
	DISPEL_MAGIC: FourCC('a002'),
	FRENZY: FourCC('a003'),
	UNHOLY_FRENZY: FourCC('a004'),
	BERSERK: FourCC('a005'),
	//City Ability
	SWAP: FourCC('a030'),
	//Guard Ability
	GUARD_INDICATOR: FourCC("A006"),
	//Spawner Abilities
	SPWN_3000: FourCC('a031'),
	SPWN_6000: FourCC('a032'),
	SPWN_ALL: FourCC('a033'),
	SPWN_RESET: FourCC('a034'),
	//Transport Abilities
	CARGO_HOLD: FourCC('a009'),
	LOAD: FourCC('a010'),
	UNLOAD_DEFAULT_HOTKEY: FourCC('Sdro'),
	UNLOAD: FourCC('a011'),
	AUTOLOAD_ON: FourCC('a013'),
	AUTOLOAD_OFF: FourCC('a014'),
	TRANSPORT_PATROL: FourCC('A008'),
	//Player Tools Abilities
	LOW_HEALTH_DEFENDER: FourCC('a051'),
	HIGH_HEALTH_DEFENDER: FourCC('a052'),
	LOW_VALUE_DEFENDER: FourCC('a053'),
	HIGH_VALUE_DEFENDER: FourCC('a054'),
	//Eliminated Player Buffs (per unit type)
	ELIMINATED_GENERAL: FourCC('A00B'),
	ELIMINATED_MARINE: FourCC('A00C'),
	ELIMINATED_ARTILLERY: FourCC('A00D'),
	ELIMINATED_MEDIC: FourCC('A00E'),
	ELIMINATED_MORTAR: FourCC('A00F'),
	ELIMINATED_RIFLEMEN: FourCC('A00G'),
	ELIMINATED_ROARER: FourCC('A00H'),
	ELIMINATED_MAJOR: FourCC('A00I'),
	ELIMINATED_KNIGHT: FourCC('A00J'),
	ELIMINATED_TANK: FourCC('A00K'),
	ELIMINATED_WARSHIP_A: FourCC('A00L'),
	ELIMINATED_WARSHIP_B: FourCC('A00M'),
	ELIMINATED_BATTLESHIP_SS: FourCC('A00N'),
	ELIMINATED_TRANSPORT_SHIP: FourCC('A00O'),
	ELIMINATED_ARMORED_TRANSPORT_SHIP: FourCC('A00P'),
};
