/**
 * Pure minimap update-loop cost estimation logic extracted for testing.
 *
 * Models the per-tick cost of `MinimapIconManager.updateAllIcons()` without
 * WC3 engine dependencies.  Used to quantify the native-call budget and
 * evaluate optimisation strategies (dirty-flagging, frequency reduction).
 */

// ---------------------------------------------------------------------------
// Per-element native call estimates
// ---------------------------------------------------------------------------

/**
 * Estimated native WC3 calls per city icon per update tick.
 *
 * Each city check:
 *  1. IsUnitVisible         (fog check)
 *  2. city.getOwner()       (internal — not a WC3 native, but triggers GetOwningPlayer)
 *  3. GetAllyColorFilterState()
 *  4. IsPlayerAlly / IsPlayerEnemy (alliance check — worst case)
 *  5. setTextureCached → potential BlzFrameSetTexture
 *
 * Average: ~5 native calls per city per tick.
 */
const CALLS_PER_CITY = 5;

/**
 * Estimated native WC3 calls per tracked unit per update tick.
 *
 * Each unit check:
 *  1. GetUnitTypeId          (validity)
 *  2. GetWidgetLife           (death check)
 *  3. IsUnitVisible           (fog)
 *  4. GetUnitX                (position X)
 *  5. GetUnitY                (position Y)
 *  6. BlzFrameSetAbsPoint     (reposition)
 *  7. getOwnerOfUnit          (SharedSlotManager lookup + GetOwningPlayer)
 *  8. BlzFrameSetTexture / cache check
 *
 * Average: ~8 native calls per unit per tick.
 */
const CALLS_PER_UNIT = 8;

/** Calls for dead-unit cleanup: hide frame + delete map entry + pool push. */
const CALLS_PER_DEAD_UNIT_CLEANUP = 3;

// ---------------------------------------------------------------------------
// Cost estimation
// ---------------------------------------------------------------------------

/**
 * Estimate the total WC3 native calls generated by one `updateAllIcons()` tick.
 *
 * @param cityCount   - Number of city icons to process.
 * @param unitCount   - Number of tracked unit icons to process.
 * @param deadCount   - Number of dead units cleaned up this tick (typically small).
 * @returns Estimated native calls for this tick.
 */
export function estimateNativeCallsPerTick(cityCount: number, unitCount: number, deadCount: number = 0): number {
	return cityCount * CALLS_PER_CITY + unitCount * CALLS_PER_UNIT + deadCount * CALLS_PER_DEAD_UNIT_CLEANUP;
}

/**
 * Estimate native calls per second at a given update frequency.
 *
 * @param callsPerTick   - Native calls per single tick.
 * @param ticksPerSecond - Update frequency (e.g. 10 for 0.1s interval).
 * @returns Native calls per second.
 */
export function estimateCallsPerSecond(callsPerTick: number, ticksPerSecond: number): number {
	return callsPerTick * ticksPerSecond;
}

// ---------------------------------------------------------------------------
// Dirty-flag optimisation for cities
// ---------------------------------------------------------------------------

/**
 * Determine whether a city icon's color needs to be recomputed.
 *
 * The current production code recomputes every city's color every tick (~200×10 = 2,000
 * calls/sec just for alliance checks).  A dirty-flag approach only updates when
 * something actually changed.
 *
 * @param currentOwner    - Current city owner (player ID or handle).
 * @param lastOwner       - Owner on previous tick.
 * @param allyModeChanged - Whether the ally color filter mode changed this tick.
 * @param fogChanged      - Whether the city's fog-of-war visibility changed this tick.
 * @returns `true` if the color should be recomputed.
 */
export function shouldUpdateCityColor(
	currentOwner: number,
	lastOwner: number,
	allyModeChanged: boolean,
	fogChanged: boolean
): boolean {
	if (currentOwner !== lastOwner) return true;
	if (allyModeChanged) return true;
	if (fogChanged) return true;
	return false;
}

/**
 * Estimate native calls saved per second by using dirty-flag for cities.
 *
 * @param totalCities    - Total city count.
 * @param dirtyCities    - How many cities actually need updating this tick.
 * @param ticksPerSecond - Update frequency.
 * @returns Native calls saved per second.
 */
export function estimateSavingsWithDirtyFlag(
	totalCities: number,
	dirtyCities: number,
	ticksPerSecond: number
): number {
	const skippedCities = totalCities - dirtyCities;
	const savedPerTick = skippedCities * CALLS_PER_CITY;
	return savedPerTick * ticksPerSecond;
}

// ---------------------------------------------------------------------------
// Frequency adjustment
// ---------------------------------------------------------------------------

/**
 * Suggest an update interval (in seconds) to stay within a native-call budget.
 *
 * Given the current tracked unit count and a per-second budget, returns
 * the longest interval that keeps total calls/sec under budget.
 *
 * The returned value is clamped to [0.03, 1.0] — faster than 33 FPS is
 * unnecessary, and slower than 1 Hz looks visually broken.
 *
 * @param trackedUnitCount - Currently tracked units.
 * @param cityCount        - Number of cities.
 * @param targetBudget     - Max native calls per second.
 * @returns Suggested timer interval in seconds.
 */
export function suggestUpdateFrequency(
	trackedUnitCount: number,
	cityCount: number,
	targetBudget: number
): number {
	const callsPerTick = estimateNativeCallsPerTick(cityCount, trackedUnitCount);
	if (callsPerTick <= 0) return 0.5; // default

	// ticks/sec = budget / callsPerTick → interval = 1 / ticks/sec
	const maxTicksPerSec = targetBudget / callsPerTick;
	const interval = 1 / maxTicksPerSec;

	// Clamp to reasonable range
	return Math.max(0.03, Math.min(1.0, interval));
}

// ---------------------------------------------------------------------------
// Constants export for tests
// ---------------------------------------------------------------------------

export { CALLS_PER_CITY, CALLS_PER_UNIT, CALLS_PER_DEAD_UNIT_CLEANUP };
